### ISSUE TITLE
Add lazy loading in App.jsx

### ISSUE THREAD

**Issue by NotStark** [fiskryeziu/zoroClone#12]
In the App.jsx file of the project repository, there's a direct import of components without lazy loading in the React Router setup. It's advisable to refactor the routes to utilize React.lazy along with Suspense for code-splitting and lazy loading of components. This would help in improving the initial loading time of the application by loading components asynchronously when they are needed.

**Comment by fiskryeziu** [comment]
What are you proposing to add as a fallback while loading skeleton or a loader

**Comment by NotStark** [comment]
> What are you proposing to add as a fallback while loading skeleton or a loader

either one of them would be fine

**Comment by fiskryeziu** [comment]
commit 48f0c4e1275dde8766a1ad082c4e5916e3b9ce81 solves the issue
