### ISSUE TITLE
Enhance Card Interaction with Play Icon on Hover

### ISSUE THREAD

**Issue by fiskryeziu** [fiskryeziu/zoroClone#5]
**Desc**
At present, the cards in the "Latest Episode" section on the home page of the website only exhibit a background color change when hovered over. 

***Steps to reproduce***
1. Open a web browser and navigate to the website: http://localhost:3000/home.
2. Scroll down the home page to locate the "Latest Episode" section.
3. Observe the cards in this section.
4. Hover the cursor over any card in the "Latest Episode" section.

**Expected Behavior:**

When a card in the "Latest Episode" section is hovered over, a play icon should appear in the middle of the card, indicating to the user that they can click to play the episode.

**Current Behavior:**

Currently, when a card is hovered over, the only visual change is a background color effect, which does not effectively convey the interaction possibility of playing the episode.

**Additional Information:**
To implement the play icon on hover, it is recommended to utilize the React Icons library.
For reference and inspiration, you can explore the website aniwatch.to/home to see how they implement a similar hover interaction with play icons on their cards.

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi @fiskryeziu  i want to work on it can you assign it to me Thanks

**Comment by fiskryeziu** [comment]
Go ahead @Muhammad-Shahid-Jamal
